import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-[#1e293b] text-white">
        
        {/* Header */}
        <header className="flex items-center justify-between px-8 py-4 border-b border-white/10 bg-[#0f172a]">
          <h1 className="text-lg font-semibold">AI Code Reviewer</h1>
          <p className="text-sm text-gray-400">
            Developed by Udit U Gunagi
          </p>
        </header>

        {/* Main Content */}
        <main className="flex-1 px-4 py-12">
          {children}
        </main>

        {/* Footer */}
        <footer className="border-t border-white/10 bg-[#0f172a] py-4 text-center text-white">
          Built with FastAPI • OpenRouter • Next.js
        </footer>

      </body>
    </html>
  );
}