import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#020617] text-white">
        
        <header className="flex justify-between items-center px-8 py-4 border-b border-white/10 bg-white/5 backdrop-blur-md">
          <h1 className="text-lg font-semibold">AI Code Reviewer</h1>
          <p className="text-sm text-gray-400">Devloped BY Udit U Gunagi</p>
        </header>

        <main className="flex-1 flex items-center justify-center px-4 pb-8">
          {children}
        </main>

        <footer className="text-center text-sm text-gray-400 py-4 border-t border-white/10 bg-white/5 backdrop-blur-md">
          Built with FastAPI • OpenRouter • Next.js
        </footer>

      </body>
    </html>
  );
}